// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenKHS.Data;

namespace OpenKHS.Data.Migrations
{
    [DbContext(typeof(OpenKHSContext))]
    partial class OpenKHSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("OpenKHS.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssigneeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueWeekStarting")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("TypeId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("OpenKHS.Models.AssignmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssignmentTypes");
                });

            modelBuilder.Entity("OpenKHS.Models.LocalCongregationMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attendant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AwaySpeaker")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmBibleReading")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmCbsConductor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmCbsReader")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmChairman")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmGems")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmLacParts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmMainHallOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmSchoolAssistant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmSchoolBibleStudy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmSchoolInitialCall")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmSchoolReturnVisit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmSchoolTalk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmSecondSchoolCounselor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmSecondSchoolOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmTreasures")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MainWtConductor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Platform")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PmChairman")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Prayer")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PublicSpeaker")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RovingMic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Security")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundDesk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WtConductor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WtReader")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LocalCongregationMembers");
                });

            modelBuilder.Entity("OpenKHS.Models.UnavailablePeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocalCongregationMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalCongregationMemberId");

                    b.ToTable("UnavailablePeriods");
                });

            modelBuilder.Entity("OpenKHS.Models.Assignment", b =>
                {
                    b.HasOne("OpenKHS.Models.LocalCongregationMember", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.AssignmentType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenKHS.Models.UnavailablePeriod", b =>
                {
                    b.HasOne("OpenKHS.Models.LocalCongregationMember", "LocalCongregationMember")
                        .WithMany()
                        .HasForeignKey("LocalCongregationMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
