// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenKHS.Data;

namespace OpenKHS.Data.Migrations
{
    [DbContext(typeof(OpenKHSContext))]
    partial class OpenKHSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("OpenKHS.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssigneeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("TypeId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("OpenKHS.Models.AssignmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssignmentTypes");
                });

            modelBuilder.Entity("OpenKHS.Models.ClmmSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplyYourselfToTheMinistryTalkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attendant1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attendant2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attendant3Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attendant4Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BibleReadingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChairmanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClosingPrayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CongregationBibleStudyConductorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CongregationBibleStudyReaderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Demo1HouseholderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Demo1PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Demo2HouseholderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Demo2PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Demo3HouseholderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Demo3PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GemsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LivingAsChristiansPart1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LivingAsChristiansPart2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LivingAsChristiansPart3Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpeningPrayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TreasuresId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WeekStarting")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplyYourselfToTheMinistryTalkId");

                    b.HasIndex("Attendant1Id");

                    b.HasIndex("Attendant2Id");

                    b.HasIndex("Attendant3Id");

                    b.HasIndex("Attendant4Id");

                    b.HasIndex("BibleReadingId");

                    b.HasIndex("ChairmanId");

                    b.HasIndex("ClosingPrayerId");

                    b.HasIndex("CongregationBibleStudyConductorId");

                    b.HasIndex("CongregationBibleStudyReaderId");

                    b.HasIndex("Demo1HouseholderId");

                    b.HasIndex("Demo1PublisherId");

                    b.HasIndex("Demo2HouseholderId");

                    b.HasIndex("Demo2PublisherId");

                    b.HasIndex("Demo3HouseholderId");

                    b.HasIndex("Demo3PublisherId");

                    b.HasIndex("GemsId");

                    b.HasIndex("LivingAsChristiansPart1Id");

                    b.HasIndex("LivingAsChristiansPart2Id");

                    b.HasIndex("LivingAsChristiansPart3Id");

                    b.HasIndex("OpeningPrayerId");

                    b.HasIndex("TreasuresId");

                    b.ToTable("ClmmSchedules");
                });

            modelBuilder.Entity("OpenKHS.Models.LocalCongregationMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attendant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AwaySpeaker")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmBibleReading")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmCbsConductor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmCbsReader")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmChairman")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmGems")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmLacParts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmMainHallOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmSchoolAssistant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmSchoolBibleStudy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmSchoolInitialCall")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmSchoolReturnVisit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmSchoolTalk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmSecondSchoolCounselor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmSecondSchoolOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClmmTreasures")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MainWtConductor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Platform")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PmChairman")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Prayer")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PublicSpeaker")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RovingMic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Security")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundDesk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WtConductor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WtReader")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LocalCongregationMembers");
                });

            modelBuilder.Entity("OpenKHS.Models.UnavailablePeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocalCongregationMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalCongregationMemberId");

                    b.ToTable("UnavailablePeriods");
                });

            modelBuilder.Entity("OpenKHS.Models.Assignment", b =>
                {
                    b.HasOne("OpenKHS.Models.LocalCongregationMember", "Assignee")
                        .WithMany("Assignments")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.AssignmentType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenKHS.Models.ClmmSchedule", b =>
                {
                    b.HasOne("OpenKHS.Models.Assignment", "ApplyYourselfToTheMinistryTalk")
                        .WithMany()
                        .HasForeignKey("ApplyYourselfToTheMinistryTalkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "Attendant1")
                        .WithMany()
                        .HasForeignKey("Attendant1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "Attendant2")
                        .WithMany()
                        .HasForeignKey("Attendant2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "Attendant3")
                        .WithMany()
                        .HasForeignKey("Attendant3Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "Attendant4")
                        .WithMany()
                        .HasForeignKey("Attendant4Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "BibleReading")
                        .WithMany()
                        .HasForeignKey("BibleReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "Chairman")
                        .WithMany()
                        .HasForeignKey("ChairmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "ClosingPrayer")
                        .WithMany()
                        .HasForeignKey("ClosingPrayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "CongregationBibleStudyConductor")
                        .WithMany()
                        .HasForeignKey("CongregationBibleStudyConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "CongregationBibleStudyReader")
                        .WithMany()
                        .HasForeignKey("CongregationBibleStudyReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "Demo1Householder")
                        .WithMany()
                        .HasForeignKey("Demo1HouseholderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "Demo1Publisher")
                        .WithMany()
                        .HasForeignKey("Demo1PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "Demo2Householder")
                        .WithMany()
                        .HasForeignKey("Demo2HouseholderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "Demo2Publisher")
                        .WithMany()
                        .HasForeignKey("Demo2PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "Demo3Householder")
                        .WithMany()
                        .HasForeignKey("Demo3HouseholderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "Demo3Publisher")
                        .WithMany()
                        .HasForeignKey("Demo3PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "Gems")
                        .WithMany()
                        .HasForeignKey("GemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "LivingAsChristiansPart1")
                        .WithMany()
                        .HasForeignKey("LivingAsChristiansPart1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "LivingAsChristiansPart2")
                        .WithMany()
                        .HasForeignKey("LivingAsChristiansPart2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "LivingAsChristiansPart3")
                        .WithMany()
                        .HasForeignKey("LivingAsChristiansPart3Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "OpeningPrayer")
                        .WithMany()
                        .HasForeignKey("OpeningPrayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenKHS.Models.Assignment", "Treasures")
                        .WithMany()
                        .HasForeignKey("TreasuresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenKHS.Models.UnavailablePeriod", b =>
                {
                    b.HasOne("OpenKHS.Models.LocalCongregationMember", "LocalCongregationMember")
                        .WithMany()
                        .HasForeignKey("LocalCongregationMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
